### ISSUE TITLE
Add some stone age tutorial stats

### ISSUE THREAD

**Issue by robbyoconnor** [wwphp-fb/stats#11]
So the group gets a lot of people who write tutorials but have no business doing so. Let's add some stats around that.

**Comment by petk** [comment]
Hello, thank you so much for reporting issues and adding suggestions. Having low quality content mentioned in the stats wouldn't have much point to promote that. Stats posts kind of aim for better quality only and to show appreciation to users who contribute. The low quality posts get the notices on the posts themselves. So, sorry but this is not on the roadmap ATM.

Have a nice day.
